server:
  port: 8801

eureka:
  instance:
    hostname: eureka-shop-app.herokuapp.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: https://eureka-shop-app.herokuapp.com/eureka/