name: Build project
on: 
  push:
    branches: 
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Java
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Deploy eureka Service
        uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: eureka-shop-app
          heroku_email: conyyy833@gmail.com
          appdir: "eureka"

      - name: Deploy Store Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: storeservice-app
          heroku_email: conyyy833@gmail.com
          appdir: "store"

      - name: Deploy Warranty Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: warrantyservice-app
          heroku_email: conyyy833@gmail.com
          appdir: "warranty"


      - name: Deploy Warehouse Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: warehouseservice-app
          heroku_email: conyyy833@gmail.com
          appdir: "warehouse"


      - name: Deploy Order Service
        uses: akhileshns/heroku-deploy@v3.4.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: orderservice-app
          heroku_email: conyyy833@gmail.com
          appdir: "order"

      - name: Run API Tests
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          collection: postman/postman-collection.json
          environment: postman/postman-heroku-environment.json
          delayRequest: 50
          reporters: cli
